require ("core.plugin_config.packer")
require ("core.plugin_config.theme")
require ("core.plugin_config.lualine")
require ("core.plugin_config.nvim-tree")
require ("core.plugin_config.telescope")
require ("core.plugin_config.treesitter")
require ("core.plugin_config.transparent")
require ("core.plugin_config.lspconfig")
-- require ("core.plugin_config.mason")
require ("core.plugin_config.nullls")
