#! /bin/sh

bspc rule -r "*"

nordvpn connect &
pamac-tray &
xrdb ~/.Xresources &
sxhkd &
nitrogen --restore &
dropbox &
picom --config ~/.config/picom.conf &
# volumeicon &
blueman-tray &
caffeine &
~/.config/polybar/launch.sh &
sleep 1 && /usr/lib64/polkit-gnome/polkit-gnome-authentication-agent-1 &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor HDMI2 -d  I II III IV V VI VII VIII IX X
bspc monitor eDP1 -d  I II III IV V VI VII VIII IX X

# Dracula Theme
bspc config normal_border_color "#44475a"
#bspc config active_border_color "#bd93f9"
#bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

# Cyan Alternative
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"


# bspc config border_width         2
# bspc config window_gap          5

bspc config border_width 2
bspc config window_gap 10
bspc config top_padding 20
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^8'
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
