#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Colors
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"
bspc config normal_border_color "#44475a"
# bspc config active_border_color "#bd93f9"
# bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"

# Launch apps
~/.config/polybar/launch.sh &
/usr/bin/emacs --daemon &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# nitrogen --restore &
feh --bg-scale ~/.config/SunDracula.jpg
picom --experimental-backend --config ~/.config/picom.conf &
dunst &
blueman-applet &
redshift &
nm-applet &
xfce4-power-manager &
pamac-tray &
xautolock -time 15 -locker blurlock &
dropbox &
/opt/piavpn/bin/pia-client &
solaar -w hide &
