#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

pgrep -x sxhkd > /dev/null ||sxhkd &

bspc config border_width         2
bspc config window_gap          1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# bspc config normal_border_color "#44475a"
# bspc config active_border_color "#bd93f9"
# bspc config focused_border_color "#ff79c6"
# bspc config presel_feedback_color "#6272a4"
# bspc config normal_border_color "#44475a"
# # bspc config active_border_color "#bd93f9"
# # bspc config focused_border_color "#ff79c6"
# bspc config presel_feedback_color "#6272a4"
# bspc config active_border_color "#6272a4"
# bspc config focused_border_color "#8be9fd"

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

/usr/bin/emacs --daemon &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# nitrogen --restore &
# feh --bg-scale ~/.dotfiles/.config/wallpaper/SynthwavePlanet.jpg &
wal -i .config/wallpaper/Mountain-Palm-Trees.jpg &
picom &
dunst &
blueman-applet &
redshift &
nm-applet &
xfce4-power-manager &
pamac-tray &
xautolock -time 15 -locker blurlock &
dropbox &
/opt/piavpn/bin/pia-client &
solaar -w hide &
~/.config/polybar/launch.sh &
